[tool.poetry]
name = "handsome"
version = "0.1.0"
description = "discord bot for handsome boys"
authors = ["Andrew Herbig <notandrewherbig@gmail.com>"]

[tool.poetry.scripts]
bot = "handsome:main"

[tool.poetry.dependencies]
python = "^3.8"
"discord.py" = {git = "https://github.com/Rapptz/discord.py.git", extras = ["voice"]}
toml = "^0.10.2"
pydantic = "^1.8.1"
aioredis = "^1.3.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.8.0"
pre-commit = "^2.12.1"
flake8 = "^3.9.1"
pyupgrade = "^2.13.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
